name: Deploy to FTPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠 Build site
        run: npm run build

      - name: 🚀 Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@@v4.3.5
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./src
